artifact_location: file:///C:/Users/Admin/PycharmProjects/mlflow/mlops_comp/mlops_exp/0
creation_time: 1726507242929
experiment_id: '0'
last_update_time: 1726507242929
lifecycle_stage: active
name: Default
