artifact_location: file:///C:/Users/Admin/PycharmProjects/mlflow/mlops_comp/mlops_exp/219954780917631341
creation_time: 1726507242967
experiment_id: '219954780917631341'
last_update_time: 1726507242967
lifecycle_stage: active
name: experiment_mlops
